### ISSUE TITLE
Problem with bw file formation (bdg2bw) - overlapping peaks

### ISSUE THREAD

**Issue by sventurkalj** [dbrg77/scATAC_snake#1]
Hi, 

I am using this pipeline to analyse a dataset produced by the protocol described in this publication. 

The pipeline runs properly and produces all the outputs. However, I am encountering a problem with the BigWig file formation using bdg2bw: when the script attempts to create a bw file, it stops with the following message:
 
Error - overlapping regions in bedGraph line 7105828 of aggregate/aggregated_scATAC_treat_pileup.bdg.sort.clip. 

In fact, if I try to load this file to the UCSC Genome Browser, it says it cannot load it because it is not a big wig file. 
After googling this error, it seems that macs2 can produce overlapping peaks, and it can occasionally produce elements that span past the end of chromosomes (both problems reported here: https://groups.google.com/a/soe.ucsc.edu/g/genome/c/_UqYFuzBwL4). This prevents the successful creation of a bw file. 
I tried to use the bedClip -truncate function to eliminate these elements, and then the bedGraphToBigWig function to produce a bw file, but this time I got the error that a particular line contains the end before the start. 

Therefore, I am not sure how to successfully produce a bw file in this case. Also, I was wondering whether this problem with macs2 might interfere with downstream analysis. 

Did you notice these sorts of errors while running the pipeline? Any suggestion will be highly appreciated.

**Comment by dbrg77** [comment]
Hi,

Thanks for the report. Indeed, I did come across that problem occasionally in the past. I don't think it will affect downstream analysis, as this only affects the visualisation. The count table is what we used for downstream analysis, which is not computed from the bdg/bw.

To produce a good `bw` file, I now modify the content of `bdg2bw`. The file `bdg2bw` is actually a `.sh` file, which calls `bedClip` and `bedGraphToBigWig`. What I did is to change the content of `bdg2bw` to the following:

```
#!/bin/bash

# check commands: slopBed, bedGraphToBigWig and bedClip

which bedtools &>/dev/null || { echo "bedtools not found! Download bedTools: <http://code.google.com/p/bedtools/>"; exit 1; }
which bedGraphToBigWig &>/dev/null || { echo "bedGraphToBigWig not found! Download: <http://hgdownload.cse.ucsc.edu/admin/exe/>"; exit 1; }
which bedClip &>/dev/null || { echo "bedClip not found! Download: <http://hgdownload.cse.ucsc.edu/admin/exe/>"; exit 1; }

# end of checking

if [ $# -lt 2 ];then
    echo "Need 2 parameters! <bedgraph> <chrom info>"
    exit
fi

F=$1
G=$2

cat ${F} | bedClip stdin ${G} ${F}.clip

LC_COLLATE=C sort -k1,1 -k2,2n ${F}.clip > ${F}.sort.clip

bedGraphToBigWig ${F}.sort.clip ${G} ${F/bdg/bw}

rm -f ${F}.clip ${F}.sort.clip
```

You see the line `cat ${F} | bedClip stdin ${G} ${F}.clip`. Here, I'm calling `bedClip` without the `truncate` mode, so it simply drop the records that are beyond the chromsome limit. I guess this should not really affect the analysis.

In general, `bedClip` will also drop the lines whose end is smaller than the start. To give you an example:

This is the content of `test.bdg`:
```
chr1	90	80	10
chr1	100	200	10
chr1	105	100	20
chr1	150	200	10
chr1	0	350	10
```

This is the content of `test.size`:
```
chr1	300
```

Then I run:

```
$ cat test.bdg | bedClip -verbose=2 stdin test.size /dev/stdout
### kent source version 386 ###
Clipping end <= start line 1 of stdin: chr1:90-80
chr1	100	200	10
Clipping end <= start line 3 of stdin: chr1:105-100
chr1	150	200	10
Clipping end > chromSize(300) line 5 of stdin: chr1:0-350
```

Only two records are saved.

I haven't really had that problem after I changed the content of the `bdg2bw` file.

I hope this helps, and let me know if it works.

Regards,
Xi

**Comment by sventurkalj** [comment]
Hi,

thank you very much for the quick reply. This addition to the bdg2bw file makes sense.

Indeed, it worked perfectly with this modification - it created a valid bw file and I was able to visualise the peaks in the UCSC Genome Browser.

Thank you!

Regards,
Sven

**Comment by dbrg77** [comment]
Great! Good to know it works.

Closing now.

Xi
